project_name = "bevy-osc-app"

geodynamo-url = "https://geoffsee.github.io/geodynamo/"

[test]
command = ["bun", "run", "test"]
format_command = ["bun", "run", "format"]



[agent_models]
claude  = "claude-opus-4-8"

#[security_scan]
#paths = [
## todo
#]
